//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books.Domain.Shared.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainError {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainError() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Books.Domain.Shared.Resources.DomainError", typeof(DomainError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ProfileIsRequired {
            get {
                return ResourceManager.GetString("ProfileIsRequired", resourceCulture);
            }
        }
        
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        public static string MaximumNameSize {
            get {
                return ResourceManager.GetString("MaximumNameSize", resourceCulture);
            }
        }
        
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        public static string AuthorsIsRequired {
            get {
                return ResourceManager.GetString("AuthorsIsRequired", resourceCulture);
            }
        }
        
        public static string BookIdIsRequired {
            get {
                return ResourceManager.GetString("BookIdIsRequired", resourceCulture);
            }
        }
        
        public static string MaximumBookIdSize {
            get {
                return ResourceManager.GetString("MaximumBookIdSize", resourceCulture);
            }
        }
        
        public static string LinkIsRequired {
            get {
                return ResourceManager.GetString("LinkIsRequired", resourceCulture);
            }
        }
        
        public static string MaximumLinkSize {
            get {
                return ResourceManager.GetString("MaximumLinkSize", resourceCulture);
            }
        }
        
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        public static string MaximumTitleSize {
            get {
                return ResourceManager.GetString("MaximumTitleSize", resourceCulture);
            }
        }
        
        public static string UserIsRequired {
            get {
                return ResourceManager.GetString("UserIsRequired", resourceCulture);
            }
        }
        
        public static string MaximumEmailSize {
            get {
                return ResourceManager.GetString("MaximumEmailSize", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string searchIsRequired {
            get {
                return ResourceManager.GetString("searchIsRequired", resourceCulture);
            }
        }
        
        public static string currentPageIsRequired {
            get {
                return ResourceManager.GetString("currentPageIsRequired", resourceCulture);
            }
        }
        
        public static string FavoriteBookNotFound {
            get {
                return ResourceManager.GetString("FavoriteBookNotFound", resourceCulture);
            }
        }
        
        public static string itemsPerPageIsRequired {
            get {
                return ResourceManager.GetString("itemsPerPageIsRequired", resourceCulture);
            }
        }
        
        public static string TheValueCannotBeGreaterThan {
            get {
                return ResourceManager.GetString("TheValueCannotBeGreaterThan", resourceCulture);
            }
        }
        
        public static string SearchMustBeAtLeastCharacters {
            get {
                return ResourceManager.GetString("SearchMustBeAtLeastCharacters", resourceCulture);
            }
        }
        
        public static string StandardProfileUserDoesNotHavePermission {
            get {
                return ResourceManager.GetString("StandardProfileUserDoesNotHavePermission", resourceCulture);
            }
        }
        
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        public static string InvalidPassowrd {
            get {
                return ResourceManager.GetString("InvalidPassowrd", resourceCulture);
            }
        }
    }
}
